language: python

python:
  - 3.6
  - 3.5
  - 2.7

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: OSXENV=py27
        - os: osx
          language: generic
          env: OSXENV=py37

before_install:
  - if [[ "${OSXENV}" == "py27" ]]; then python --version | grep "Python 2.7"; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install pip; fi
  - if [[ "${OSXENV}" == "py37" ]]; then brew install python@3; fi

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: elgalu
  password:
    secure: lqt6NjL0HstfxvzDlWoaHv+3xAGp9QSDtXqEf8u74LibjHf3jZAcm+sRWh9ExnS9HRXpnWuyAPEFqDwS2eM7rU92ihbI/tBtjHt+fg/TBgW3NfUKTPr31kMfV3QhEfvrIT8d6ZN63VDwcccwdVXPtLnNPvPRb7fxkvX1AIDJEZpbmY5hY+Fn433RzyiJykGiTlTwotagjdRauaVwlQT4dbIVtDeMFXvqMck5gOpAq+0uBnZbY1/DrGb+yo3AzkyMnr0AOr+ph6VwHLfn3gY6l/FxqIe/5eSWP23AaWH4vbzRSvVxRABSQf7s6w+zN/7sKIRoi8UbmF/xk2TA/hip3OWDJROZ7JxSQ47rHpap20OIthM56dXveAPH4+TvJVcK9tSi3KsU+N06z9fSVfcDB7bCEwqFlreBMiOm7Wxxv4h5cogMKgpia0FdQ3U2LG3/LajXvlw/s7RwxmYY3gXO1OqnmKZRvbN4RhpVdEkeorQXlbiFM3dpUuL/oF9oK6iIs2rj2y0o2Dh6k/i4CDl33ZzLFPZ1DxkykBZ5crkypPAqafd1Hp5fxNj//OmKbI38TdDydcTEe2kqA3jzCLtN9hqF7sZN82a9i9DTyHujIvzziLxQNd/TQ0zWQisFMNZxaMmrQFqYYQCn4xcRa23nV10xO8HroLiJqGfxyptAVjg=
  on:
    tags: true
    repo: zdatalake/zdatalake
    condition: ${TRAVIS_OS_NAME} == "linux"
    python: 3.6
