# Do not build on tags (GitHub only)
skip_tags: true

#faster cloning
clone_depth: 1

build_script:
  - python --version
  - which python

test_script:
  - pip --version
  - which pip
#  - choco install python3

