# which python     #=> /c/Python27/python
# which pip        #=> /c/Python27/Scripts/pip
# python --version #=> Python 2.7.15
# pip --version    #=> pip 10.0.1 from c:\python27\lib\site-packages\pip (python 2.7)
build_script:
  - python --version

test_script:
  - dir C:\Python*.*
  - ls /c/Python*.*
#  - choco install python3

# Do not build on tags (GitHub only)
skip_tags: true

#faster cloning
clone_depth: 1

platform:
- x86
- x64
